"""add_user_blocked_and_frozen_fields

Revision ID: 0b2ec2ea321b
Revises: a7c7e124aa07
Create Date: 2026-05-26 14:08:36.094230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2ec2ea321b'
down_revision: Union[str, Sequence[str], None] = 'a7c7e124aa07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('frozen_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'frozen_until')
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###
