"""add_vehicle_nfc_id_to_requests

Revision ID: 322641d1e409
Revises: d487bed4de6e
Create Date: 2026-08-13 22:15:13.456041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322641d1e409'
down_revision: Union[str, Sequence[str], None] = 'd487bed4de6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_ownership_requests', sa.Column('vehicle_nfc_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_vehicle_ownership_requests_vehicle_nfc_id'), 'vehicle_ownership_requests', ['vehicle_nfc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_ownership_requests_vehicle_nfc_id'), table_name='vehicle_ownership_requests')
    op.drop_column('vehicle_ownership_requests', 'vehicle_nfc_id')
    # ### end Alembic commands ###
