"""refactor_wallet_fuel_fk

Revision ID: 4bbd6553126a
Revises: b611460db7e6
Create Date: 2026-05-19 01:19:53.574985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbd6553126a'
down_revision: Union[str, Sequence[str], None] = 'b611460db7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'fuel_transactions', 'wallet_transactions', ['wallet_transaction_id'], ['id'])
    op.drop_constraint(op.f('wallet_transactions_fuel_transaction_id_fkey'), 'wallet_transactions', type_='foreignkey')
    op.drop_column('wallet_transactions', 'fuel_transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transactions', sa.Column('fuel_transaction_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('wallet_transactions_fuel_transaction_id_fkey'), 'wallet_transactions', 'fuel_transactions', ['fuel_transaction_id'], ['id'])
    op.drop_constraint(None, 'fuel_transactions', type_='foreignkey')
    # ### end Alembic commands ###
