"""expand_company_registration_fields

Revision ID: 6e9b7ce7af16
Revises: 1b2c3d4e5f67
Create Date: 2026-05-26 05:09:11.666232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9b7ce7af16'
down_revision: Union[str, Sequence[str], None] = '1b2c3d4e5f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('nib', sa.String(length=13), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('fleet_size', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('siup_no', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('tdp_no', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('npwp_no', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('status', sa.String(), nullable=False, server_default='Belum Verifikasi'))
    op.add_column('companies', sa.Column('siup_doc', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('tdp_doc', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('npwp_doc', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('nib_doc', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_nib'), 'companies', ['nib'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_nib'), table_name='companies')
    op.drop_column('companies', 'nib_doc')
    op.drop_column('companies', 'npwp_doc')
    op.drop_column('companies', 'tdp_doc')
    op.drop_column('companies', 'siup_doc')
    op.drop_column('companies', 'status')
    op.drop_column('companies', 'notes')
    op.drop_column('companies', 'npwp_no')
    op.drop_column('companies', 'tdp_no')
    op.drop_column('companies', 'siup_no')
    op.drop_column('companies', 'fleet_size')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'nib')
    # ### end Alembic commands ###
