"""add_sales_officer_role

Revision ID: 7187c1cd7614
Revises: 4bbd6553126a
Create Date: 2026-05-19 03:16:12.371315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7187c1cd7614'
down_revision: Union[str, Sequence[str], None] = '4bbd6553126a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_role_enum ADD VALUE IF NOT EXISTS 'SALES_OFFICER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
