"""create_fraud_logs_table

Revision ID: 7ab922849297
Revises: 0b2ec2ea321b
Create Date: 2026-05-26 14:15:27.396370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ab922849297'
down_revision: Union[str, Sequence[str], None] = '0b2ec2ea321b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.String(length=20), nullable=False),
    sa.Column('fuel_transaction_id', sa.UUID(), nullable=True),
    sa.Column('gas_station_id', sa.UUID(), nullable=False),
    sa.Column('buyer_profile_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_ownership_id', sa.UUID(), nullable=True),
    sa.Column('plate_number_snapshot', sa.String(length=50), nullable=False),
    sa.Column('nik_snapshot', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('SAFE', 'SUSPICIOUS', 'HIGH_RISK', 'CRITICAL', name='fraud_risk_level_enum'), nullable=False),
    sa.Column('action_taken', sa.Enum('ALLOW_TRANSACTION', 'WARNING', 'FREEZE_ACCOUNT', 'BLOCK_ACCOUNT', name='fraud_action_taken_enum'), nullable=False),
    sa.Column('detected_frauds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FLAGGED', 'RESOLVED', name='fraud_case_status_enum'), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['fuel_transaction_id'], ['fuel_transactions.id'], ),
    sa.ForeignKeyConstraint(['gas_station_id'], ['gas_stations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_ownership_id'], ['vehicle_ownerships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_logs_case_id'), 'fraud_logs', ['case_id'], unique=True)
    op.create_index(op.f('ix_fraud_logs_created_at'), 'fraud_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_logs_created_at'), table_name='fraud_logs')
    op.drop_index(op.f('ix_fraud_logs_case_id'), table_name='fraud_logs')
    op.drop_table('fraud_logs')
    # ### end Alembic commands ###
