"""add_vehicle_nfc_id_fields

Revision ID: 9c85a958adcd
Revises: c2023401c4a2
Create Date: 2026-08-09 08:46:27.353386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c85a958adcd'
down_revision: Union[str, Sequence[str], None] = 'c2023401c4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_transactions', sa.Column('vehicle_nfc_id_snapshot', sa.String(), nullable=True))
    op.add_column('vehicle_ownerships', sa.Column('vehicle_nfc_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_vehicle_ownerships_vehicle_nfc_id'), 'vehicle_ownerships', ['vehicle_nfc_id'], unique=False)
    op.add_column('vehicle_registry_mockup', sa.Column('vehicle_nfc_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'vehicle_registry_mockup', ['vehicle_nfc_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_registry_mockup', type_='unique')
    op.drop_column('vehicle_registry_mockup', 'vehicle_nfc_id')
    op.drop_index(op.f('ix_vehicle_ownerships_vehicle_nfc_id'), table_name='vehicle_ownerships')
    op.drop_column('vehicle_ownerships', 'vehicle_nfc_id')
    op.drop_column('fuel_transactions', 'vehicle_nfc_id_snapshot')
    # ### end Alembic commands ###
