"""add_jenis_to_vehicle_registry

Revision ID: a7c7e124aa07
Revises: 6e9b7ce7af16
Create Date: 2026-05-26 05:29:21.428439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c7e124aa07'
down_revision: Union[str, Sequence[str], None] = '6e9b7ce7af16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MOTORCYCLE', 'CAR', 'TRUCK', name='vehicle_class_enum').create(op.get_bind())
    op.add_column('vehicle_registry_mockup', sa.Column('jenis', sa.Enum('MOTORCYCLE', 'CAR', 'TRUCK', name='vehicle_class_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_registry_mockup', 'jenis')
    sa.Enum('MOTORCYCLE', 'CAR', 'TRUCK', name='vehicle_class_enum').drop(op.get_bind())
    # ### end Alembic commands ###
