"""add buyer registration tables

Revision ID: a97d72891e92
Revises: 7187c1cd7614
Create Date: 2026-05-23 06:24:46.660522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a97d72891e92'
down_revision: Union[str, Sequence[str], None] = '7187c1cd7614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


buyer_registration_status_enum = postgresql.ENUM(
    'PENDING',
    'PROCESSING',
    'FAILED',
    'VERIFIED',
    'REVIEW_REQUIRED',
    'COMPLETED',
    name='buyer_registration_status_enum',
    create_type=False,
)

buyer_document_type_enum = postgresql.ENUM(
    'KTP_PHOTO',
    'SELFIE_PHOTO',
    name='buyer_document_type_enum',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    buyer_registration_status_enum.create(op.get_bind(), checkfirst=True)
    buyer_document_type_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('buyer_registration_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nik_input', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('status', buyer_registration_status_enum, nullable=False),
    sa.Column('nik_ocr', sa.String(), nullable=True),
    sa.Column('is_nik_match', sa.Boolean(), nullable=True),
    sa.Column('registry_citizen_id', sa.UUID(), nullable=True),
    sa.Column('registry_name_snapshot', sa.String(), nullable=True),
    sa.Column('registry_kk_id_snapshot', sa.UUID(), nullable=True),
    sa.Column('registry_ktp_nfc_id_snapshot', sa.String(), nullable=True),
    sa.Column('face_match_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_face_match', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('created_user_id', sa.UUID(), nullable=True),
    sa.Column('created_buyer_profile_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('verification_started_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['registry_citizen_id'], ['citizen_registry_mockup.id'], ),
    sa.ForeignKeyConstraint(['registry_kk_id_snapshot'], ['kk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buyer_registration_attempts_created_user_id', 'buyer_registration_attempts', ['created_user_id'], unique=False)
    op.create_index('ix_buyer_registration_attempts_email', 'buyer_registration_attempts', ['email'], unique=False)
    op.create_index('ix_buyer_registration_attempts_nik_input', 'buyer_registration_attempts', ['nik_input'], unique=False)
    op.create_index('ix_buyer_registration_attempts_registry_citizen_id', 'buyer_registration_attempts', ['registry_citizen_id'], unique=False)
    op.create_index('ix_buyer_registration_attempts_status', 'buyer_registration_attempts', ['status'], unique=False)
    op.create_index('uq_buyer_registration_attempts_active_email', 'buyer_registration_attempts', ['email'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'PROCESSING', 'REVIEW_REQUIRED', 'VERIFIED')"))
    op.create_index('uq_buyer_registration_attempts_active_nik_input', 'buyer_registration_attempts', ['nik_input'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'PROCESSING', 'REVIEW_REQUIRED', 'VERIFIED')"))
    op.create_table('buyer_registration_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_attempt_id', sa.UUID(), nullable=False),
    sa.Column('document_type', buyer_document_type_enum, nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registration_attempt_id'], ['buyer_registration_attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_attempt_id', 'document_type', name='uq_buyer_registration_document_attempt_type')
    )
    op.create_table('buyer_profile_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_profile_id', sa.UUID(), nullable=False),
    sa.Column('document_type', buyer_document_type_enum, nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('source_registration_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['source_registration_document_id'], ['buyer_registration_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_profile_id', 'document_type', name='uq_buyer_profile_document_profile_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buyer_profile_documents')
    op.drop_table('buyer_registration_documents')
    op.drop_index('uq_buyer_registration_attempts_active_nik_input', table_name='buyer_registration_attempts', postgresql_where=sa.text("status IN ('PENDING', 'PROCESSING', 'REVIEW_REQUIRED', 'VERIFIED')"))
    op.drop_index('uq_buyer_registration_attempts_active_email', table_name='buyer_registration_attempts', postgresql_where=sa.text("status IN ('PENDING', 'PROCESSING', 'REVIEW_REQUIRED', 'VERIFIED')"))
    op.drop_index('ix_buyer_registration_attempts_status', table_name='buyer_registration_attempts')
    op.drop_index('ix_buyer_registration_attempts_registry_citizen_id', table_name='buyer_registration_attempts')
    op.drop_index('ix_buyer_registration_attempts_nik_input', table_name='buyer_registration_attempts')
    op.drop_index('ix_buyer_registration_attempts_email', table_name='buyer_registration_attempts')
    op.drop_index('ix_buyer_registration_attempts_created_user_id', table_name='buyer_registration_attempts')
    op.drop_table('buyer_registration_attempts')
    buyer_document_type_enum.drop(op.get_bind(), checkfirst=True)
    buyer_registration_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
