"""apply_new_domain_models

Revision ID: b611460db7e6
Revises: 
Create Date: 2026-05-19 00:29:51.780716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b611460db7e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('octane', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('DIESEL', 'GASOLINE', name='fuel_category_enum'), nullable=False),
    sa.Column('price_per_liter', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subsidy_price_per_liter', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('subsidy_type', sa.Enum('SUBSIDIZED', 'NON_SUBSIDIZED', name='subsidy_type_enum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gas_stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subsidy_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monthly_quota_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_allowed_njkb', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_registry_mockup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('manufacture_year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('engine_capacity_cc', sa.Integer(), nullable=False),
    sa.Column('pkb', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('njkb', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('owner_nik', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('USER', 'GAS_STATION', 'COMPANY', name='owner_type_enum'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citizen_registry_mockup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nik', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('ktp_nfc_id', sa.String(), nullable=False),
    sa.Column('kk_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['kk_id'], ['kk.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ktp_nfc_id'),
    sa.UniqueConstraint('nik')
    )
    op.create_table('kk_subsidy_eligibilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kk_id', sa.UUID(), nullable=False),
    sa.Column('subsidy_policy_id', sa.UUID(), nullable=False),
    sa.Column('total_njkb', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('eligibility_status', sa.Enum('ELIGIBLE', 'NOT_ELIGIBLE', name='eligibility_status_enum'), nullable=False),
    sa.Column('eligibility_reason', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kk_id'], ['kk.id'], ),
    sa.ForeignKeyConstraint(['subsidy_policy_id'], ['subsidy_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kk_vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kk_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('ownership_status', sa.Enum('OWNED', 'FAMILY_OWNED', 'COMPANY_OWNED', name='kk_vehicle_ownership_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kk_id'], ['kk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('XENDIT', 'MOCK', 'MANUAL', name='payment_provider_enum'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('provider_reference_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'EXPIRED', name='payment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', postgresql.ARRAY(sa.Enum('SUPERADMIN', 'ADMIN_GAS_STATION', 'ADMIN_COMPANY', 'BUYER', name='user_role_enum')), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('gas_station_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['gas_station_id'], ['gas_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('buyer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nik_snapshot', sa.String(), nullable=False),
    sa.Column('ktp_nfc_id_snapshot', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kk_id', sa.UUID(), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='verification_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['kk_id'], ['kk.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subsidy_quotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('BUYER_PROFILE', 'VEHICLE', name='subsidy_owner_type_enum'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('kk_subsidy_eligibility_id', sa.UUID(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quota_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('used_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kk_subsidy_eligibility_id'], ['kk_subsidy_eligibilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_ownerships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('BUYER_PROFILE', 'COMPANY', name='vehicle_owner_type_enum'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('ownership_status', sa.Enum('PERSONAL', 'COMPANY', name='vehicle_ownership_status_enum'), nullable=False),
    sa.Column('plate_number_snapshot', sa.String(), nullable=False),
    sa.Column('ktp_nfc_id_snapshot', sa.String(), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_type', sa.Enum('PERSONAL', 'COMPANY', name='buyer_type_enum'), nullable=False),
    sa.Column('buyer_profile_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_ownership_id', sa.UUID(), nullable=True),
    sa.Column('gas_station_id', sa.UUID(), nullable=False),
    sa.Column('fuel_type_id', sa.UUID(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subsidy_quota_id', sa.UUID(), nullable=True),
    sa.Column('kk_subsidy_eligibility_id', sa.UUID(), nullable=True),
    sa.Column('is_subsidized', sa.Boolean(), nullable=False),
    sa.Column('subsidized_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('non_subsidized_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('market_price_per_liter', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subsidized_price_per_liter', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('WALLET', 'CASH', 'EDC', 'QRIS', name='payment_method_enum'), nullable=False),
    sa.Column('wallet_transaction_id', sa.UUID(), nullable=True),
    sa.Column('transaction_status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', 'FAILED', name='fuel_transaction_status_enum'), nullable=False),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('plate_number_snapshot', sa.String(), nullable=False),
    sa.Column('nik_snapshot', sa.String(), nullable=True),
    sa.Column('company_name_snapshot', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ),
    sa.ForeignKeyConstraint(['gas_station_id'], ['gas_stations.id'], ),
    sa.ForeignKeyConstraint(['kk_subsidy_eligibility_id'], ['kk_subsidy_eligibilities.id'], ),
    sa.ForeignKeyConstraint(['subsidy_quota_id'], ['subsidy_quotas.id'], ),
    sa.ForeignKeyConstraint(['vehicle_ownership_id'], ['vehicle_ownerships.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TOP_UP', 'PAYMENT', 'WITHDRAWAL', 'REFUND', 'TRANSFER', name='transaction_type_enum'), nullable=False),
    sa.Column('transaction_flow', sa.Enum('IN', 'OUT', name='transaction_flow_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('counterparty_wallet_id', sa.UUID(), nullable=True),
    sa.Column('payment_transaction_id', sa.UUID(), nullable=True),
    sa.Column('fuel_transaction_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='wallet_transaction_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['fuel_transaction_id'], ['fuel_transactions.id'], ),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transactions')
    op.drop_table('fuel_transactions')
    op.drop_table('vehicle_ownerships')
    op.drop_table('subsidy_quotas')
    op.drop_table('buyer_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('payment_transactions')
    op.drop_table('kk_vehicles')
    op.drop_table('kk_subsidy_eligibilities')
    op.drop_table('citizen_registry_mockup')
    op.drop_table('wallets')
    op.drop_table('vehicle_registry_mockup')
    op.drop_table('subsidy_policies')
    op.drop_table('kk')
    op.drop_table('gas_stations')
    op.drop_table('fuel_types')
    op.drop_table('companies')
    # ### end Alembic commands ###
