"""add_foto_ktp_to_citizen_registry

Revision ID: c2023401c4a2
Revises: de1c631bf13f
Create Date: 2026-08-09 02:39:18.591409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c2023401c4a2'
down_revision: Union[str, Sequence[str], None] = 'de1c631bf13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_registry_mockup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('engine_capacity_cc', sa.Integer(), nullable=True),
    sa.Column('pkb', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('njkb', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('owner_nik', sa.String(), nullable=True),
    sa.Column('jenis', postgresql.ENUM('MOTORCYCLE', 'CAR', 'TRUCK', name='vehicle_class_enum', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('citizen_registry_mockup', sa.Column('foto_ktp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen_registry_mockup', 'foto_ktp')
    op.drop_table('vehicle_registry_mockup')
    # ### end Alembic commands ###
