"""make_buyer_profile_id_nullable_and_add_company_id

Revision ID: d487bed4de6e
Revises: 9c85a958adcd
Create Date: 2026-08-13 21:52:47.927140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd487bed4de6e'
down_revision: Union[str, Sequence[str], None] = '9c85a958adcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_ownership_requests', sa.Column('company_id', sa.UUID(), nullable=True))
    op.alter_column('vehicle_ownership_requests', 'buyer_profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_vehicle_ownership_requests_company_id'), 'vehicle_ownership_requests', ['company_id'], unique=False)
    op.create_foreign_key(None, 'vehicle_ownership_requests', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_ownership_requests', type_='foreignkey')
    op.drop_index(op.f('ix_vehicle_ownership_requests_company_id'), table_name='vehicle_ownership_requests')
    op.alter_column('vehicle_ownership_requests', 'buyer_profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('vehicle_ownership_requests', 'company_id')
    # ### end Alembic commands ###
