"""refactor_ktp_subsidy

Revision ID: de1c631bf13f
Revises: d169b42c6a8d
Create Date: 2026-08-06 12:14:39.346793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de1c631bf13f'
down_revision: Union[str, Sequence[str], None] = 'd169b42c6a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subsidy_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('income_threshold', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('default_quota_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('occupation_bonuses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_vehicle_registry_mockup_owner_nik'), table_name='vehicle_registry_mockup')
    op.drop_index(op.f('ix_vehicle_registry_mockup_plate_number'), table_name='vehicle_registry_mockup')
    op.drop_index(op.f('ix_vehicle_registry_mockup_registration_number'), table_name='vehicle_registry_mockup')
    op.drop_table('vehicle_registry_mockup')
    op.add_column('citizen_registry_mockup', sa.Column('pekerjaan', sa.String(), nullable=True))
    op.add_column('citizen_registry_mockup', sa.Column('penghasilan', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen_registry_mockup', 'penghasilan')
    op.drop_column('citizen_registry_mockup', 'pekerjaan')
    op.create_table('vehicle_registry_mockup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plate_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('manufacture_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('engine_capacity_cc', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pkb', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('njkb', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('owner_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_nik', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('jenis', postgresql.ENUM('MOTORCYCLE', 'CAR', 'TRUCK', name='vehicle_class_enum'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_registry_mockup_pkey'))
    )
    op.create_index(op.f('ix_vehicle_registry_mockup_registration_number'), 'vehicle_registry_mockup', ['registration_number'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_mockup_plate_number'), 'vehicle_registry_mockup', ['plate_number'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_mockup_owner_nik'), 'vehicle_registry_mockup', ['owner_nik'], unique=False)
    op.drop_table('subsidy_settings')
    # ### end Alembic commands ###
